### ISSUE TITLE
Not saving the game at all (sometimes crashing)

### ISSUE THREAD

**Issue by The12MT** [PipeRift/SaveExtension#14]
**Describe the bug**
The game doesn´t save at all for me. It doesnt matter if in standalone, PIE or built game! Also there are some problems with asynch saving. (can´t test loading) Sometimes the game crashes while loading.. mostly in the built game.

**To Reproduce**
1. use world composition
2. I am not sure about that... i just added the save to slot to my persistent level

**Logs**
[The12MT_2.log](https://github.com/PipeRift/SaveExtension/files/2775567/The12MT_2.log)

**[Optional] Screenshots if any**
<img width="716" alt="save" src="https://user-images.githubusercontent.com/25091110/51427465-9eb4d000-1bf8-11e9-80a2-9249933bfca0.PNG">
i made sure there are more saveslots in the plugin settings than actually in the game!

**Environment (please complete the following information):**
 - Engine Version: 4.21.1
 - Plugin Version: 1.1a
 - OS: Windows

**[Optional] Additional context**

**Comment by The12MT** [comment]
Error when crashing


Access violation - code c0000005 (first/second chance not available)

VCRUNTIME140
UE4Editor_SaveExtension!FMemoryWriter::Serialize() [d:\rocketsync\4.21.0-4541578+++ue4+release-4.21\working\engine\source\runtime\core\public\serialization\memorywriter.h:53]
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_Engine
UE4Editor_SaveExtension!FSerializeActorsTask::SerializeActor() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\saveextension\source\saveextension\private\slotdatatask_saver.cpp:212]
UE4Editor_SaveExtension!FSerializeActorsTask::SerializeGameState() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\saveextension\source\saveextension\private\slotdatatask_saver.cpp:113]
UE4Editor_SaveExtension!FSerializeActorsTask::DoWork() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\saveextension\source\saveextension\private\slotdatatask_saver.cpp:39]
UE4Editor_SaveExtension!FAsyncTask<FSerializeActorsTask>::DoWork() [d:\rocketsync\4.21.0-4541578+++ue4+release-4.21\working\engine\source\runtime\core\public\async\asyncwork.h:264]
UE4Editor_SaveExtension!FAsyncTask<FSerializeActorsTask>::DoThreadedWork() [d:\rocketsync\4.21.0-4541578+++ue4+release-4.21\working\engine\source\runtime\core\public\async\asyncwork.h:288]
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
kernel32
ntdll

**Comment by muit** [comment]
Thanks for the report, will fix it asap!

**Comment by muit** [comment]
So here we have two possible problems.
For now I will see this issue as if its only about the crash.

We can talk over discord about your other issue, since I fear I need more details :)

**Comment by muit** [comment]
Same issue as #17 Will continue there

**Comment by muit** [comment]
Unfortunately, I couldn't reproduce this issue, may you be able to provide me a simple test project where it happens?
