### ISSUE TITLE
Blueprint nativization

### ISSUE THREAD

**Issue by thesameguy2323** [PipeRift/SaveExtension#15]
I'm packaging my game to android and I'm getting an error when I use blueprint nativization for the game mode and other blueprints that uses these nods (save to id) or (delete from id) or (load from id) but this only started to happen after update SE 1.1a

you can enable Blueprint nativization 
1-Packaging>bluprints>Blueprint nativization method>inclusive
2-packaging to etc2
3-packaging failed

here is the error 
(\Android\Game\Source\NativizedAssets\Private\gamecar__pf3099619019.cpp(808,118) :  error: 'DeleteSlotFromId' is a private member of 'USaveManager')

and here is the full warnings and errors
[New Text Document (3).txt](https://github.com/PipeRift/SaveExtension/files/2799200/New.Text.Document.3.txt)

 - Engine Version: 4.20.3
 - Plugin Version: 1.1a
 - OS: windows 10

P.S I can't use save manager and save to id nods in functions anymore only in event graph, why?

**Comment by muit** [comment]
Thanks for the report, will get on it in a few weeks

**Comment by thesameguy2323** [comment]
any news about the fix?
