### ISSUE TITLE
SaveData cast failed 

### ISSUE THREAD

**Issue by quintendc** [PipeRift/SaveExtension#16]
**Describe the bug**

**To Reproduce**
1. create custom preset
2. define preset in Project settings
3. add variables to your Custom SlotData
4. try to read variables from the custom SlotData through SaveManager.GetCurrentData -> Cast to Custom SlotData this will fail the GetCurrentData returns the default Preset/SlotData

see demo project 

**Logs**
https://pastebin.com/0KmHN87p

**Environment (please complete the following information):**
 - Engine Version: 4.21.2
 - Plugin Version: 1.1a
 - OS: Windows

**[Optional] Additional context**
demo project https://we.tl/t-ApXklsc7UZ

**Comment by quintendc** [comment]
in a build project it is using the SaveExtension default Preset and not the custom one i suppose, since the GetCurrentData always return SlotData

**Comment by muit** [comment]
Hi @quintendc
Please fill the issue's information related to logs, versions, description etc.
Its hard to reproduce a bug without it.

Thanks for reporting!

**Comment by quintendc** [comment]
@muit i included the logs see URL, and updated the issue information
you can also use the demo project you will see when you click the Random int button in the UI is will print a string cast failed

**Comment by muit** [comment]
Thanks, will be very useful :)

**Comment by muit** [comment]
Hi @quintendc, may I get the link for your test project again? Seems to be invalid

**Comment by muit** [comment]
Will close while the link is fixed for tracking purposes.
Thanks for reporting it.
