### ISSUE TITLE
Crash when saving world with multiple landscapes streamed to it

### ISSUE THREAD

**Issue by SuperCoder7979** [PipeRift/SaveExtension#17]
When trying to save a level with multiple landscapes streamed to it, the game crashes. This has been confirmed that it is due to a multithreading issue. However, after testing with multithreading disabled, the issue still persists.

**To Reproduce**
1. Save a world with multiple landscapes streamed to it using save extension.

**Environment:**
 - Engine Version: 4.21.1
 - Plugin Version: 1.1
 - OS: Windows

**Additional context**
Crash logs:

Crashes before disabling multithreading:
https://pastebin.com/2nncysPn
https://pastebin.com/Z3XqKdFC

Crash after disabling multithreading:
https://pastebin.com/KNU7Zte8

**Comment by muit** [comment]
Unfortunately, I couldn't reproduce this issue, may you be able to provide me a simple test project where it happens?

**Comment by muit** [comment]
I will close this issue for tracking purposes until new information is received.
Thanks for reporting it.

**Comment by Acrossfy** [comment]
I had the same issue on 1.2, but only with default value for max slots (0). After increasing it - crash disappears.
