### ISSUE TITLE
SaveExtensionInterface to be used from C++

### ISSUE THREAD

**Issue by TriageWilsonC** [PipeRift/SaveExtension#20]
Currently the SaveExtensionInterface functions are BlueprintImplementableEvent so they can only be implemented in blueprints but not C++. It would be convenient if they could be changed to BlueprintNativeEvent so we can implement in C++ or blueprints.

I mentioned it in the Discord channel and the developer said he'd fix it in the next release, but I'm posting it here hoping it'll be easier to keep track of. Sorry for mentioning it twice. 

Thanks so much for making this plugin by the way, especially for free! It's super helpful so far.

**Comment by muit** [comment]
Thank you for posting it here! :P It was on my radar

**Comment by TriageWilsonC** [comment]
Thanks so much for addressing this so fast :) Looking forward to it!
