### ISSUE TITLE
Saving Async crash the game

### ISSUE THREAD

**Issue by lucastucious** [PipeRift/SaveExtension#25]
**Describe the bug**
When i save the game, with the blueprint "save slot to id", in Async Mode on serialization in settings, the game crashed. It occurs only when i have sublevels. When i try on sublevels only, no crash at all.

**To Reproduce**
Add multiple sublevels, with blueprint on it.
Make sure you're on AsyncMode on serialization
Save the game with "Save slot to id"

**Logs**
https://pastebin.com/sLMu8rF7

**Environment (please complete the following information):**
 - Engine Version: 4.21.2
 - Plugin Version: 1.1a
 - OS: Windows 7 64 bit

**Comment by muit** [comment]
Hi,
I think this issue was already reported at #17 

If you could provide an example project where I can reproduce the issue it would be super useful.

Thanks for reporting it!
muit

**Comment by lucasdlk** [comment]
Hey ! Thanks for the quick response !
I've made this example project for you : https://mega.nz/#!J48QlC4R!bpgc3kEgDqhJQf6SeHUKS_DOXlKTHN4CYajSf7RkGlI

Sorry, you have to load the Main level in TEST\Maps

**Comment by muit** [comment]
Awesome! I will give it a look :)

**Comment by lucasdlk** [comment]
To save, you have tu push "Tab" key

**Comment by lucasdlk** [comment]
Any news ?

**Comment by muit** [comment]
Well your project helped me reproduce it, but I am not very sure where the problem is originated.

Simplest fix is the move from inclusive to exclusive saving. Thats something that the community approved on Discord. Its kind of a refactor.

"This happens because of X, I dont know what X is, but I can go around it and probably fix it at the same time"

Thats kind of the explanation haha

**Comment by muit** [comment]
This issue doesnt correlate anymore with the current architecture of the plugin. That means it is probably fixed. If after 1.4 this is not the case, please let us know!

Thanks a lot!
Miguel
