### ISSUE TITLE
Load game delete actors

### ISSUE THREAD

**Issue by lucastucious** [PipeRift/SaveExtension#26]
**Describe the bug**
My game save all of my sublevel, as i can see in the log. But when i load, it load every level but one. I can't figure why this one in particular... 
Level can perfectly be saved or load when he is alone.
Maybe it's linked on my other issue : https://github.com/PipeRift/SaveExtension/issues/25

**Logs**
https://pastebin.com/Neep16ck

**Environment (please complete the following information):**
 - Engine Version: 4.21.1
 - Plugin Version: 1.1a
 - OS: Windows 7 64 Bit

**Comment by muit** [comment]
Hi,
since you have those suspicions lets try to see if I can fix issue #25 with the example project.

**Comment by muit** [comment]
Many fixes related to this have been done for 1.4 (releasing soon). Please feel free to come back once it releases and let us know if it worked!

Thank you!
Miguel
