### ISSUE TITLE
ignored actors not working

### ISSUE THREAD

**Issue by thesameguy2323** [PipeRift/SaveExtension#28]
**Describe the bug**
ignored actors it used to work on 1.1a, now the plugin loads the ignored actors
under project manager / Save Extension

 - Engine Version: 4.20
 - OS: win10

**Comment by muit** [comment]
As an small puntual note, the way actors are ignored has been improved (fixing this issue) and will come with the new Pipeline feature (#24) on the next version.

**Comment by muit** [comment]
This is fixed but will be included with Save graphs (#39).
Closing for tracking purposes.

**Comment by thesameguy2323** [comment]
when the next update is going to be available?
 date if it's possible please and thank you
