### ISSUE TITLE
save async crashes and default preset won't update

### ISSUE THREAD

**Issue by seddonmb** [PipeRift/SaveExtension#30]
**Describe the bug**
Hi, 'Save Async' always crashes the game.
I have tried to work around this by changing the default preset to 'only sync' or 'load async.

This works during editor, but if Editor is relaunched, the default has REVERTED back to 'save async' (even making my own preset gets updated by this default!)

As the packaged game also crashes, I'm assuming the default is reverting back before cook.

**To Reproduce**

**Logs**
It's helps us a lot to have a log. If you can, drop the last one here.
*Logs can be found under "MyProject/Saved/Logs/MyProject.log"*

**[Optional] Screenshots if any**
If applicable, add screenshots or videos to help explain your problem.

**Environment (please complete the following information):**
 engine 4.21.2
plugin 1.2

So far this is making the plugin impossible to use on a packaged game.

**Comment by muit** [comment]
Hi Seddon,

Thank you very much for the report! The save async crash is a known issue (#17 ) but the preset problem is new so I wont mark is as duplicated.

Will work to fix it
muit

**Comment by muit** [comment]
This issue is not relevant anymore due to 1.4 release fixes.
Closing for tracking.

Thanks!
muit
