### ISSUE TITLE
On github there is no working 4.24 version.

### ISSUE THREAD

**Issue by benjamink152** [PipeRift/SaveExtension#47]
**Describe the feature requested**
When, how, what is the request about

**How does it help the user (you)?**
Ex. It reduces the amount of work I have to do

**Is it related to a problem?**

**[Optional] Propose an approach to the feature (the less we think the better!)**
How would it work? Ex. I would suggest using instanced objects

**Any other possible approach?**

**[Optional] Additional context**
Add any other context or screenshots about the feature request

**Comment by muit** [comment]
Hi @benjamink152,

There is the 4.24 branch and on releases 4.24 and 4.25 files.

Greetings,
Miguel
