### ISSUE TITLE
Level BP variables don't get saved

### ISSUE THREAD

**Issue by fg16** [PipeRift/SaveExtension#5]
**Describe the bug**

Global Variables placed in the 'level blueprint' don't save / load at all

**To Reproduce**

Save to ID with S 
Load from ID with L 
On the properties of variables check box 'SaveGame'

Variables are still not saving and every load generates a lot of console errors on the logs.

**Expected behavior**

Variables saving and loading properly

**Environment (please complete the following information):**

 - Engine Version: 4.21.1
 - Plugin Version: v1.0
 - OS: Windows 10 Insider v1709 and V1809 both tested

**Comment by muit** [comment]
@fg16  could I ask you to attach that log? It would help a lot. Thanks!

**Comment by muit** [comment]
Will see what possible fixes there are. For now, this bug is confirmed :)

**Comment by muit** [comment]
Turns out, level scripts were being cleaned away when loading. Its now fixed
