### ISSUE TITLE
UnrealEngine 4.25 crashes when loading a destroyed Actor

### ISSUE THREAD

**Issue by ngzaharias** [PipeRift/SaveExtension#50]
USlotDataTask_Loader::RespawnActors will crash when spawning the actor because the FActorSpawnParameters::NameMode is set to ESpawnActorNameMode::Fatal and during loading it finds an actor with the same name.

I was able to get things working by changing the FActorSpawnParameters::NameMode to ESpawnActorNameMode::Requested.

**To Reproduce**
1. Start Level
2. Save Game
3. Destroy an Actor
4. Load Game

**Comment by muit** [comment]
Hi @ngzaharias,

I was able to reproduce this issue.

Thank you for the report!
muit
