### ISSUE TITLE
BP Array of Structs SaveGame Variable wiping contents

### ISSUE THREAD

**Issue by elevins** [PipeRift/SaveExtension#51]
**Describe the bug**
If the variable you want to save for an actor is in the form of an array of structs the data will be wiped clear after Loading. 

**To Reproduce**
1. Create an actor with a variable of type: Array of Struct (Any BP Struct)
2. Give the actor's variable some default values (or set values before save)
3. Implement Save Extension and Save/Load the game
4. After Load the variable will have empty values 

**Environment (please complete the following information):**
 - Engine Version: 4.24.2
 - Plugin Version: 1.2
 - OS: Windows 10

**Comment by muit** [comment]
Hi @elevins,

Do this blueprint structs have their variables marked as save game?
I tested this and variables on an array of blueprint structs saved correctly.

**Comment by muit** [comment]
Closing for tracking purposes. Feel free to re-open.
