### ISSUE TITLE
Blueprint property marked as SaveGame doesn't get saved

### ISSUE THREAD

**Issue by DethRaid** [PipeRift/SaveExtension#52]
**Describe the bug**
When I load a game, the property marked as SaveGame on my blueprint actor doesn't get loaded - it has the value it had before I loaded the game, not the value it had when I saved the game

**To Reproduce**
- Create a Blueprint actor
- Implement the SaveExtensionInterface on the Blueprint actor
- Create an integer property, check the `SaveGame` box
- Script up some way to change that property
- Start playing in editor
- Save the game
- Change the property from before
- Load the game
- Observe that your implementation of `ISaveExtensionInterface::OnLoadFinished`, which prints out the value of the property, has printed out the value of the property after you changed it, not the value that the property had when the game was saved

**Logs**
My log is under NDA, but I can tell you that I don't see any messages from SaveExtensino in my log

**Environment (please complete the following information):**
 - Engine Version: 4.25
 - Plugin Version: 1.2
 - OS: Windows 20 64-bit

**Comment by DethRaid** [comment]
Removing the `ISaveGameInterface` from my actor has no appreciable effect

**Comment by Mephiztopheles** [comment]
having a similar problem. Tried using the actorFilter, but didn't change a thing. None of the interface functions get called.

**Comment by muit** [comment]
Hi guys,

ISaveGameInterface doesn't have anything to do with the saving process. @Mephiztopheles if you want their events to be called you need to register the interface in the manager:
![image](https://user-images.githubusercontent.com/3672970/92964642-bf3c3880-f474-11ea-8066-a28a1c79c568.png)

@DethRaid was this blueprint included in the ActorFilter on the preset? Actors and Components that are not in the filter will be completely ignored.

**Comment by Mephiztopheles** [comment]
@muit I just mentioned the interface to say, that I tried it that way

**Comment by muit** [comment]
Yeah I understand, maybe it wasnt the same issue in the end though. Not sure.

Oh, no absolutely not :) the interface is just a way to get notified when saving happens, but its not specific to the actor.
See LifetimeComponent, its a simplification over the interface, and it auto-registers (its neat, try it).

Having this component and the interface carries a cost. So putting it on a player is fine, but I wouldn't put it on an actor that gets saved 5000 times haha

**Comment by DethRaid** [comment]
> Hi guys,
> 
> ISaveGameInterface doesn't have anything to do with the saving process. @Mephiztopheles if you want their events to be called you need to register the interface in the manager:
> ![image](https://user-images.githubusercontent.com/3672970/92964642-bf3c3880-f474-11ea-8066-a28a1c79c568.png)
> 
> @DethRaid was this blueprint included in the ActorFilter on the preset? Actors and Components that are not in the filter will be completely ignored.

I definitely tried adding my Blueprint AActor-derived class to the ActorFilter but didn't get the results I wanted

If ISaveGameInterface isn't an interface about saving... what is it?

**Comment by Mephiztopheles** [comment]
and we still can't save (or load) the actors...

**Comment by muit** [comment]
We will soon release 1.4 with many fixes. SOme of them are related to this topics so feel free to let us know if it still happens :)
