### ISSUE TITLE
Save Extension not working in packaged Win64 game 

### ISSUE THREAD

**Issue by 0xff0000** [PipeRift/SaveExtension#54]
**Describe the bug**
In a UE 4.25.1 in a BP project SaveExtension is used to store and load a bunch of custom BP's descendant from Actor BP with various variables including arrays of custom BP Structs. 
All is working in the editor, but when packaged for Win64 (don't have an opportunity to test for other platforms atm) the Save procedure completes, but the save files sized are smaller then in editor mode and content differs. On load packeged game either does nothing or crashes.

**To Reproduce**
1. Create a BP project from a ThirdPersonGame template with no starter content.
2. Create a simple custom BP class from Actor, lets call it TestActor
3. Add a component to TestActor, f.e. a 2d sprite.
4. In ThirdPersonCharacter BP bind to keyboard buttons V,C,X - spawn TestActor, StoreGameToSlotID (0), LoadSoltFromID (0) correspondingly.
5. Test game in editor, everything works fine: TestActor spawn at player's character position, game is saved on C press and loaded on X.
6. Pack game for Win64.
7. Run a packaged game. 
8. Loading is not working anymore (most likely including because of Saving not working properly).

**Environment (please complete the following information):**
 - Engine Version: 4.25.1
 - Plugin Version: 1.2 from marketplace
 - OS: Windows 10

**Comment by zenithcreator** [comment]
I'm having this same issue in Engine Version 4.25.1, Plugin Version **1.3** from marketplace. Any help would be greatly appreciated.

**Comment by muit** [comment]
Thank you for the report!
This issue has likely been fixed and will release with 1.4. You can also just download the github version of the plugin directly.
