### ISSUE TITLE
Having a very annoying crashing while saving

### ISSUE THREAD

**Issue by SankaDaVinci** [PipeRift/SaveExtension#56]
So, what is basically happening is, everytime I save the game, it crashes and reports a access violation code coming from the plugin its the famous Access violation - code c0000005. It only happens when I us ethe boolean called Override if needed.

**Comment by muit** [comment]
That is interesting. Could you provide a testing project where this issue can be reproduced?

Thanks for the report!
muit

**Comment by muit** [comment]
Closing for tracking purposes. Feel free to come back with details if available :)
