### ISSUE TITLE
Name conflict with 4.26 engine release

### ISSUE THREAD

**Issue by yajiedesign** [PipeRift/SaveExtension#57]
Build failed with UE4 master Because the official added a class called FActorClassFilter  

https://github.com/EpicGames/UnrealEngine/blob/master/Engine/Plugins/Developer/TraceSourceFiltering/Source/SourceFilteringCore/Public/DataSourceFiltering.h#L45

**Comment by muit** [comment]
Dammit... Thanks for telling us
