### ISSUE TITLE
UE4 - Crash when 'Store Game Instance' is ticked

### ISSUE THREAD

**Issue by 5p4rky** [PipeRift/SaveExtension#58]
The UE4 editor is randomly crashing (freezing) whenever the 'Store Game Instance' checkbox is selected in Project Settings>Serialization. I have checked the logs and there is no error messaging. And there is no crash report being produced. The editor becomes unresponsive while the game is playing. The crashing also happens at random intervals, sometimes after a few seconds of play, sometimes a few minutes after play and appears to be random. The crash can also happen when nothing is being pressed/played,

**Comment by 5p4rky** [comment]
Should also note that when this box is unticked i have not been getting the crash, this is the only setting that has been checked (hence why i believe it is the issue)

**Comment by muit** [comment]
Hi @5p4rky,

I tried to reproduce this issue but didn't get any crash.
Could you provide a test project where this is reproducible?

Thank you!
Muit

**Comment by muit** [comment]
Closing for tracking purposes. Feel free to re-open!

**Comment by muit** [comment]
An automated test has been added and GameInstanced still save okay.
I unfortunately need a test project to see this crash.
