### ISSUE TITLE
Cannot make the plugin work

### ISSUE THREAD

**Issue by Andergraw** [PipeRift/SaveExtension#60]
**Describe the bug**
Maybe I am the bug. I am not able of loading any state as in examples. 

**To Reproduce**
Follow most basic example from Documentation or Marketplace

**Logs**
It's helps us a lot to have a log. If you can, drop the last one here.
*Logs can be found under "MyProject/Saved/Logs/MyProject.log"*

**[Optional] Screenshots if any**
If applicable, add screenshots or videos to help explain your problem.

**Environment (please complete the following information):**
 - Engine Version: [e.g. 4.25.3]
 - Plugin Version: [e.g. 1.3 & 1.4]
 - OS: [e.g. Windows]

**[Optional] Additional context**
I feel pretty stupid, but I have been trying to make this plugin work without success. I am following the example from the Marketplace, I have tried with that version (BTW, it is marked as 1.3 but the file says 1.2) and the latest beta (1.4).
I've been following this Youtube video and...no way. No matter what, I can't manage to load a state as in the video. Neither physical objets (position, rotation, etc) nor variable states. The plugin is saving (I can see the files and the screenshot) but when I click "Load", nothing changes. I can tell the "Load slot from ID" node has been called but no luck. This plugin does exactly what I need for this current project, if I could get any help it would be awesome.

Thanks,

**Comment by muit** [comment]
Hi @Andergraw,
That sounds like you need to setup filters on the preset. See quick-start inside docs folder (the docs website is not updating right now unfortunately :( )

Also, stay up to date with 1.4 release since its going to a good one :)

**Comment by muit** [comment]
Let me know if filters did it (or ping me on discord!)

Closing for tracking purposes

Thanks,
muit

**Comment by Andergraw** [comment]
It worked! Now we are getting our hands dirty on the plugin. Thanks!!
