### ISSUE TITLE
Interface functions not called

### ISSUE THREAD

**Issue by SkacikPL** [PipeRift/SaveExtension#64]
Tested on custom built 4.25 with plugin built from current source.

None of the interface functions are being called.
Using **SaveExtensionInterface** in any blueprint class and implementing any of the functions within that class will not result in interface functions being called when they should (start/end of saving/loading).

This _may_ be an issue with custom built versions of engine as i ran across some google results implying similar issues with implementing C++ interfaces in blueprints where functions would not be called.

So far i attempted a full UE4 4.25 rebuild along with game module and the plugin to no avail.
Rest of the plugin functions as it should.

**Comment by muit** [comment]
Hi! Thank you for posting!

Have you registered the object into the savemanager? It is a manual process unfortunately

**Comment by SkacikPL** [comment]
> Have you registered the object into the savemanager? It is a manual process unfortunately

Ah i see now,

Yeah that is less than optimal but it works.
I guess that should be outlined somewhere in the documentation (i imagine the interface itself should be mentioned at least once).

**Comment by muit** [comment]
Its not optimal for the user, but it is for performance. I may look for a better solution in the future.

Good point, I sometimes lack the time or simply forget important things like this.
Thank you for posting, it helps a lot!

**Comment by SkacikPL** [comment]
No problem, thanks for the plugin.
Besides wasting couple hours on rebuilding entire engine, it still saved me order of magnitude more on trying to lay out my own way of serializing things. Especially since i'm _not so technically inclined._

So a net positive result after all.
