### ISSUE TITLE
4.26 precompiled version

### ISSUE THREAD

**Issue by TushieSushi** [PipeRift/SaveExtension#69]
I'm having a lot of issues compiling the plugin for 4.26

**Comment by ShaneYu** [comment]
I doubt that anyone is going to help you with this issue if you've not put any description as to your issues. At some point I am sure they will release a new version, but in the meantime you're not going to get anywhere like this 😉

**Comment by muit** [comment]
Sorry for the long delay. Its been a while.

4.26 will not be supported anymore, but it should compile fine with the latest code available. 5.2 instead is on the works.

Muit
