### ISSUE TITLE
UE5 Version

### ISSUE THREAD

**Issue by htrampe** [PipeRift/SaveExtension#76]
Hi! I would be great if we can get a new Version for UE5 :) ! THX

**Comment by saurabhguptarock** [comment]
Any update on this?
Please add this feature 🙏

**Comment by ACMOIDRE** [comment]
thanks for plugin.
when will this  plugin updated to UE5

**Comment by muit** [comment]
Hi :)

#88 is a WIP for an update to 5.2 (5.3 soon too)

Muit
