### ISSUE TITLE
Seperate Get Slot Info by Id and Get Slot Info

### ISSUE THREAD

**Issue by RYRY1002** [PipeRift/SaveExtension#81]
**Describe the feature requested**
Currently when creating a save there are 2 nodes that you can use: Save Slot, Save Slot by Id and Save Slot by Info.
But when requesting Slot Info, you can only request by Slot Id, making it impossible to get Slot Info from a save slot that doesn't use an Id.

**How does it help the user (you)?**
It makes it possible for me to request Slot Info for save that don't use Id's.
I am creating a save menu, one of its features will be to allow players to see a thumbnail for the save, its map and how long ago it was saved.

**[Optional] Propose an approach to the feature (the less we think the better!)**
Ideally, Get Slot Info nodes would be arranged the same way as the Save Slot nodes.
There would be a Get Slot Info node (for name based slots), and a Get Slot Info by Id (for Id based slots).
Obviously, there wouldn't be a Get Slot Info by Info node, because that wouldn't make any sense.

**[Optional] Additional context**
![image](https://user-images.githubusercontent.com/56659369/215681790-2291ece4-11c3-4ed6-9549-86c1bb681d8b.png)

**Comment by RYRY1002** [comment]
Update: for the time being I have edited the plugin in order to allow for this functionality, but an official implementation would definitely be an awesome addition to this plugin.

**Comment by muit** [comment]
Thanks for the suggestion @RYRY1002! :)
Feedback like this is very valuable.

I would have loved to see your modification, but meanwhile I created a PR with the change already.

Greeting,
Miguel
